### PR TITLE
SEARCH-624: Add status-id to results

### PR DESCRIPTION
**Pull request by amCap1712**

### CODE REVIEW

**Review by yvanzo — COMMENTED** [review]
Thanks! LGTM but it requires status ID to be added to release search index first. I will do so.

**Review by yvanzo — CHANGES_REQUESTED** [review]
Related changes to the indexer in metabrainz/sir#113 have been merged.

@amCap1712: A rebase a required due to your cleanup in `oxml.xml` and test files.

**Comment by amCap1712** [comment]
Rebased successfully.

**Comment by yvanzo** [comment]
Some bits have been forgotten in the process, like removing reference to `StringStatusAdapter` from `oxml.xml` at line 58.

See your previous commit [89de89b](https://github.com/metabrainz/mb-solr/commit/89de89b272ea1177089dddd899e5f1e6b58a7ad0#diff-aeea2613c7f90fa14ce483c90038cbdc06374ead335d4341bb28c2355c9635c1L251-R251) for reference.

**Review by yvanzo — APPROVED** [review]
Thanks, I reordered release attributes in commit https://github.com/metabrainz/mb-solr/pull/41/commits/f24305f922d074ed9bcb9a115a6da687b06d100e to fix CI tests.

**Comment by amCap1712** [comment]
Thanks for the review and the related changes!

**Pull request merged**
